parameters:
    berriart_apm.listener.class: Berriart\Bundle\APMBundle\EventListener\KernelListener
    berriart_apm.handler.class: Berriart\Bundle\APMBundle\Client\ClientHandler
    berriart_apm.Client.app_insights.class: Berriart\Bundle\APMBundle\Client\AppInsightsClient

services:
    berriart_apm.listener.exception:
        class: %berriart_apm.listener.class%
        arguments: ['@kernel', '@berriart_apm.handler']
        tags:
            -  name: kernel.event_listener
               event: kernel.exception
               method: onKernelException
               priority: 0
            -  name: kernel.event_listener
               event: kernel.request
               method: onKernelRequest
               priority: 0
            -  name: kernel.event_listener
               event: kernel.terminate
               method: onKernelTerminate
               priority: 0
    berriart_apm.handler:
        class: %berriart_apm.handler.class%
    berriart_apm.Client.app_insights:
        class: %berriart_apm.Client.app_insights.class%
    %berriart_apm.service.alias%:
        alias: berriart_apm.handler
