language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/phpmd/phpmd/src/bin/phpmd ./ text  phpmd.xml --exclude vendor
  - ./vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpcpd ./ --exclude=vendor

notifications:
  email: alberto@berriart.com